// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.24.2
// source: api/services/runtime/v1/runtime.proto

package runtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeResource_GetCapabilities_FullMethodName    = "/cubelet.services.runtime.v1.RuntimeResource/GetCapabilities"
	RuntimeResource_PrepareSandbox_FullMethodName     = "/cubelet.services.runtime.v1.RuntimeResource/PrepareSandbox"
	RuntimeResource_ReleaseSandbox_FullMethodName     = "/cubelet.services.runtime.v1.RuntimeResource/ReleaseSandbox"
	RuntimeResource_InspectSandbox_FullMethodName     = "/cubelet.services.runtime.v1.RuntimeResource/InspectSandbox"
	RuntimeResource_ReconcileSandboxes_FullMethodName = "/cubelet.services.runtime.v1.RuntimeResource/ReconcileSandboxes"
)

// RuntimeResourceClient is the client API for RuntimeResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeResource exposes node-resource operations to CubeShim.
//
// This service is intentionally not a CRI, image, snapshot, container, task, or
// sandbox runtime. Implementations MUST NOT call Cubelet embedded containerd to
// create the same sandbox. The host containerd remains the sole owner of OCI
// images, snapshots, CNI ordering, and Kubernetes sandbox/task state.
type RuntimeResourceClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	PrepareSandbox(ctx context.Context, in *PrepareSandboxRequest, opts ...grpc.CallOption) (*PrepareSandboxResponse, error)
	ReleaseSandbox(ctx context.Context, in *ReleaseSandboxRequest, opts ...grpc.CallOption) (*ReleaseSandboxResponse, error)
	InspectSandbox(ctx context.Context, in *InspectSandboxRequest, opts ...grpc.CallOption) (*InspectSandboxResponse, error)
	// ReconcileSandboxes is report-only in v1. Cleanup always requires an
	// explicit idempotent ReleaseSandbox call.
	ReconcileSandboxes(ctx context.Context, in *ReconcileSandboxesRequest, opts ...grpc.CallOption) (*ReconcileSandboxesResponse, error)
}

type runtimeResourceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeResourceClient(cc grpc.ClientConnInterface) RuntimeResourceClient {
	return &runtimeResourceClient{cc}
}

func (c *runtimeResourceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, RuntimeResource_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeResourceClient) PrepareSandbox(ctx context.Context, in *PrepareSandboxRequest, opts ...grpc.CallOption) (*PrepareSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSandboxResponse)
	err := c.cc.Invoke(ctx, RuntimeResource_PrepareSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeResourceClient) ReleaseSandbox(ctx context.Context, in *ReleaseSandboxRequest, opts ...grpc.CallOption) (*ReleaseSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSandboxResponse)
	err := c.cc.Invoke(ctx, RuntimeResource_ReleaseSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeResourceClient) InspectSandbox(ctx context.Context, in *InspectSandboxRequest, opts ...grpc.CallOption) (*InspectSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSandboxResponse)
	err := c.cc.Invoke(ctx, RuntimeResource_InspectSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeResourceClient) ReconcileSandboxes(ctx context.Context, in *ReconcileSandboxesRequest, opts ...grpc.CallOption) (*ReconcileSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileSandboxesResponse)
	err := c.cc.Invoke(ctx, RuntimeResource_ReconcileSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeResourceServer is the server API for RuntimeResource service.
// All implementations must embed UnimplementedRuntimeResourceServer
// for forward compatibility.
//
// RuntimeResource exposes node-resource operations to CubeShim.
//
// This service is intentionally not a CRI, image, snapshot, container, task, or
// sandbox runtime. Implementations MUST NOT call Cubelet embedded containerd to
// create the same sandbox. The host containerd remains the sole owner of OCI
// images, snapshots, CNI ordering, and Kubernetes sandbox/task state.
type RuntimeResourceServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	PrepareSandbox(context.Context, *PrepareSandboxRequest) (*PrepareSandboxResponse, error)
	ReleaseSandbox(context.Context, *ReleaseSandboxRequest) (*ReleaseSandboxResponse, error)
	InspectSandbox(context.Context, *InspectSandboxRequest) (*InspectSandboxResponse, error)
	// ReconcileSandboxes is report-only in v1. Cleanup always requires an
	// explicit idempotent ReleaseSandbox call.
	ReconcileSandboxes(context.Context, *ReconcileSandboxesRequest) (*ReconcileSandboxesResponse, error)
	mustEmbedUnimplementedRuntimeResourceServer()
}

// UnimplementedRuntimeResourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeResourceServer struct{}

func (UnimplementedRuntimeResourceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedRuntimeResourceServer) PrepareSandbox(context.Context, *PrepareSandboxRequest) (*PrepareSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareSandbox not implemented")
}
func (UnimplementedRuntimeResourceServer) ReleaseSandbox(context.Context, *ReleaseSandboxRequest) (*ReleaseSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSandbox not implemented")
}
func (UnimplementedRuntimeResourceServer) InspectSandbox(context.Context, *InspectSandboxRequest) (*InspectSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectSandbox not implemented")
}
func (UnimplementedRuntimeResourceServer) ReconcileSandboxes(context.Context, *ReconcileSandboxesRequest) (*ReconcileSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileSandboxes not implemented")
}
func (UnimplementedRuntimeResourceServer) mustEmbedUnimplementedRuntimeResourceServer() {}
func (UnimplementedRuntimeResourceServer) testEmbeddedByValue()                         {}

// UnsafeRuntimeResourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeResourceServer will
// result in compilation errors.
type UnsafeRuntimeResourceServer interface {
	mustEmbedUnimplementedRuntimeResourceServer()
}

func RegisterRuntimeResourceServer(s grpc.ServiceRegistrar, srv RuntimeResourceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeResourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeResource_ServiceDesc, srv)
}

func _RuntimeResource_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeResourceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeResource_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeResourceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeResource_PrepareSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeResourceServer).PrepareSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeResource_PrepareSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeResourceServer).PrepareSandbox(ctx, req.(*PrepareSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeResource_ReleaseSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeResourceServer).ReleaseSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeResource_ReleaseSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeResourceServer).ReleaseSandbox(ctx, req.(*ReleaseSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeResource_InspectSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeResourceServer).InspectSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeResource_InspectSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeResourceServer).InspectSandbox(ctx, req.(*InspectSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeResource_ReconcileSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeResourceServer).ReconcileSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeResource_ReconcileSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeResourceServer).ReconcileSandboxes(ctx, req.(*ReconcileSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeResource_ServiceDesc is the grpc.ServiceDesc for RuntimeResource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeResource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.runtime.v1.RuntimeResource",
	HandlerType: (*RuntimeResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _RuntimeResource_GetCapabilities_Handler,
		},
		{
			MethodName: "PrepareSandbox",
			Handler:    _RuntimeResource_PrepareSandbox_Handler,
		},
		{
			MethodName: "ReleaseSandbox",
			Handler:    _RuntimeResource_ReleaseSandbox_Handler,
		},
		{
			MethodName: "InspectSandbox",
			Handler:    _RuntimeResource_InspectSandbox_Handler,
		},
		{
			MethodName: "ReconcileSandboxes",
			Handler:    _RuntimeResource_ReconcileSandboxes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/runtime/v1/runtime.proto",
}
