// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/runtime/v1/runtime.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxResourceState int32

const (
	SandboxResourceState_SANDBOX_RESOURCE_STATE_UNSPECIFIED SandboxResourceState = 0
	SandboxResourceState_SANDBOX_RESOURCE_STATE_PREPARING   SandboxResourceState = 1
	SandboxResourceState_SANDBOX_RESOURCE_STATE_READY       SandboxResourceState = 2
	SandboxResourceState_SANDBOX_RESOURCE_STATE_RELEASING   SandboxResourceState = 3
	SandboxResourceState_SANDBOX_RESOURCE_STATE_RELEASED    SandboxResourceState = 4
	SandboxResourceState_SANDBOX_RESOURCE_STATE_ERROR       SandboxResourceState = 5
)

// Enum value maps for SandboxResourceState.
var (
	SandboxResourceState_name = map[int32]string{
		0: "SANDBOX_RESOURCE_STATE_UNSPECIFIED",
		1: "SANDBOX_RESOURCE_STATE_PREPARING",
		2: "SANDBOX_RESOURCE_STATE_READY",
		3: "SANDBOX_RESOURCE_STATE_RELEASING",
		4: "SANDBOX_RESOURCE_STATE_RELEASED",
		5: "SANDBOX_RESOURCE_STATE_ERROR",
	}
	SandboxResourceState_value = map[string]int32{
		"SANDBOX_RESOURCE_STATE_UNSPECIFIED": 0,
		"SANDBOX_RESOURCE_STATE_PREPARING":   1,
		"SANDBOX_RESOURCE_STATE_READY":       2,
		"SANDBOX_RESOURCE_STATE_RELEASING":   3,
		"SANDBOX_RESOURCE_STATE_RELEASED":    4,
		"SANDBOX_RESOURCE_STATE_ERROR":       5,
	}
)

func (x SandboxResourceState) Enum() *SandboxResourceState {
	p := new(SandboxResourceState)
	*p = x
	return p
}

func (x SandboxResourceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxResourceState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (SandboxResourceState) Type() protoreflect.EnumType {
	return &file_api_services_runtime_v1_runtime_proto_enumTypes[0]
}

func (x SandboxResourceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxResourceState.Descriptor instead.
func (SandboxResourceState) EnumDescriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type ReconcileDisposition int32

const (
	ReconcileDisposition_RECONCILE_DISPOSITION_UNSPECIFIED      ReconcileDisposition = 0
	ReconcileDisposition_RECONCILE_DISPOSITION_LIVE             ReconcileDisposition = 1
	ReconcileDisposition_RECONCILE_DISPOSITION_ORPHAN_CANDIDATE ReconcileDisposition = 2
	ReconcileDisposition_RECONCILE_DISPOSITION_MISSING          ReconcileDisposition = 3
)

// Enum value maps for ReconcileDisposition.
var (
	ReconcileDisposition_name = map[int32]string{
		0: "RECONCILE_DISPOSITION_UNSPECIFIED",
		1: "RECONCILE_DISPOSITION_LIVE",
		2: "RECONCILE_DISPOSITION_ORPHAN_CANDIDATE",
		3: "RECONCILE_DISPOSITION_MISSING",
	}
	ReconcileDisposition_value = map[string]int32{
		"RECONCILE_DISPOSITION_UNSPECIFIED":      0,
		"RECONCILE_DISPOSITION_LIVE":             1,
		"RECONCILE_DISPOSITION_ORPHAN_CANDIDATE": 2,
		"RECONCILE_DISPOSITION_MISSING":          3,
	}
)

func (x ReconcileDisposition) Enum() *ReconcileDisposition {
	p := new(ReconcileDisposition)
	*p = x
	return p
}

func (x ReconcileDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconcileDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_runtime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (ReconcileDisposition) Type() protoreflect.EnumType {
	return &file_api_services_runtime_v1_runtime_proto_enumTypes[1]
}

func (x ReconcileDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconcileDisposition.Descriptor instead.
func (ReconcileDisposition) EnumDescriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

type GetCapabilitiesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientApiVersion uint32                 `protobuf:"varint,1,opt,name=client_api_version,json=clientApiVersion,proto3" json:"client_api_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *GetCapabilitiesRequest) GetClientApiVersion() uint32 {
	if x != nil {
		return x.ClientApiVersion
	}
	return 0
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetCapabilitiesResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion   uint32                 `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Capabilities []*Capability          `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// v1 MUST return "node-resources-only".
	ServiceMode string `protobuf:"bytes,3,opt,name=service_mode,json=serviceMode,proto3" json:"service_mode,omitempty"`
	// Unix socket used for one-shot TAP delivery with SCM_RIGHTS. File
	// descriptors are never encoded in protobuf.
	FdHandoffEndpoint string `protobuf:"bytes,4,opt,name=fd_handoff_endpoint,json=fdHandoffEndpoint,proto3" json:"fd_handoff_endpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *GetCapabilitiesResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *GetCapabilitiesResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetServiceMode() string {
	if x != nil {
		return x.ServiceMode
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetFdHandoffEndpoint() string {
	if x != nil {
		return x.FdHandoffEndpoint
	}
	return ""
}

type PodIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodIdentity) Reset() {
	*x = PodIdentity{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodIdentity) ProtoMessage() {}

func (x *PodIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodIdentity.ProtoReflect.Descriptor instead.
func (*PodIdentity) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *PodIdentity) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PodIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodIdentity) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VcpuCount     uint32                 `protobuf:"varint,1,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceRequest) GetVcpuCount() uint32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *ResourceRequest) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type NetworkIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network namespace already created by host containerd/CNI.
	NetnsPath     string   `protobuf:"bytes,1,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	InterfaceName string   `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PodIp         string   `protobuf:"bytes,3,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Dns           []string `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkIntent) Reset() {
	*x = NetworkIntent{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkIntent) ProtoMessage() {}

func (x *NetworkIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkIntent.ProtoReflect.Descriptor instead.
func (*NetworkIntent) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkIntent) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

func (x *NetworkIntent) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkIntent) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *NetworkIntent) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

type PrepareSandboxRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Stable across retries of the same desired generation.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Monotonically increases when the caller replaces a sandbox with the same ID.
	Generation    uint64           `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Pod           *PodIdentity     `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	Resources     *ResourceRequest `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Network       *NetworkIntent   `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSandboxRequest) Reset() {
	*x = PrepareSandboxRequest{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSandboxRequest) ProtoMessage() {}

func (x *PrepareSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSandboxRequest.ProtoReflect.Descriptor instead.
func (*PrepareSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PrepareSandboxRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PrepareSandboxRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PrepareSandboxRequest) GetPod() *PodIdentity {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *PrepareSandboxRequest) GetResources() *ResourceRequest {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PrepareSandboxRequest) GetNetwork() *NetworkIntent {
	if x != nil {
		return x.Network
	}
	return nil
}

type RuntimeAssets struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KernelPath     string                 `protobuf:"bytes,1,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	AgentPath      string                 `protobuf:"bytes,2,opt,name=agent_path,json=agentPath,proto3" json:"agent_path,omitempty"`
	GuestImagePath string                 `protobuf:"bytes,3,opt,name=guest_image_path,json=guestImagePath,proto3" json:"guest_image_path,omitempty"`
	SharedRoot     string                 `protobuf:"bytes,4,opt,name=shared_root,json=sharedRoot,proto3" json:"shared_root,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeAssets) Reset() {
	*x = RuntimeAssets{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeAssets) ProtoMessage() {}

func (x *RuntimeAssets) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeAssets.ProtoReflect.Descriptor instead.
func (*RuntimeAssets) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeAssets) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *RuntimeAssets) GetAgentPath() string {
	if x != nil {
		return x.AgentPath
	}
	return ""
}

func (x *RuntimeAssets) GetGuestImagePath() string {
	if x != nil {
		return x.GuestImagePath
	}
	return ""
}

func (x *RuntimeAssets) GetSharedRoot() string {
	if x != nil {
		return x.SharedRoot
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Scope         uint32                 `protobuf:"varint,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *Route) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Route) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Route) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Route) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Route) GetScope() uint32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

type Neighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Neighbor) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Neighbor) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Neighbor) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type NetworkAttachment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NetworkHandle      string                 `protobuf:"bytes,1,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	TapName            string                 `protobuf:"bytes,2,opt,name=tap_name,json=tapName,proto3" json:"tap_name,omitempty"`
	GuestInterfaceName string                 `protobuf:"bytes,3,opt,name=guest_interface_name,json=guestInterfaceName,proto3" json:"guest_interface_name,omitempty"`
	Mac                string                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	Mtu                uint32                 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Ips                []string               `protobuf:"bytes,6,rep,name=ips,proto3" json:"ips,omitempty"`
	Routes             []*Route               `protobuf:"bytes,7,rep,name=routes,proto3" json:"routes,omitempty"`
	Neighbors          []*Neighbor            `protobuf:"bytes,8,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkAttachment) Reset() {
	*x = NetworkAttachment{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAttachment) ProtoMessage() {}

func (x *NetworkAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAttachment.ProtoReflect.Descriptor instead.
func (*NetworkAttachment) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkAttachment) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *NetworkAttachment) GetTapName() string {
	if x != nil {
		return x.TapName
	}
	return ""
}

func (x *NetworkAttachment) GetGuestInterfaceName() string {
	if x != nil {
		return x.GuestInterfaceName
	}
	return ""
}

func (x *NetworkAttachment) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkAttachment) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkAttachment) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *NetworkAttachment) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkAttachment) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type PreparedSandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Assets        *RuntimeAssets         `protobuf:"bytes,4,opt,name=assets,proto3" json:"assets,omitempty"`
	Network       *NetworkAttachment     `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparedSandbox) Reset() {
	*x = PreparedSandbox{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedSandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedSandbox) ProtoMessage() {}

func (x *PreparedSandbox) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedSandbox.ProtoReflect.Descriptor instead.
func (*PreparedSandbox) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *PreparedSandbox) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PreparedSandbox) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *PreparedSandbox) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PreparedSandbox) GetAssets() *RuntimeAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *PreparedSandbox) GetNetwork() *NetworkAttachment {
	if x != nil {
		return x.Network
	}
	return nil
}

type PrepareSandboxResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Sandbox *PreparedSandbox       `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	// True when an idempotent retry returned an existing matching generation.
	Reused        bool `protobuf:"varint,2,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSandboxResponse) Reset() {
	*x = PrepareSandboxResponse{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSandboxResponse) ProtoMessage() {}

func (x *PrepareSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSandboxResponse.ProtoReflect.Descriptor instead.
func (*PrepareSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *PrepareSandboxResponse) GetSandbox() *PreparedSandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *PrepareSandboxResponse) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type ReleaseSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Generation     uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseSandboxRequest) Reset() {
	*x = ReleaseSandboxRequest{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSandboxRequest) ProtoMessage() {}

func (x *ReleaseSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSandboxRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReleaseSandboxRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReleaseSandboxRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ReleaseSandboxRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReleaseSandboxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True both after a successful release and when the generation was absent.
	Released      bool `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSandboxResponse) Reset() {
	*x = ReleaseSandboxResponse{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSandboxResponse) ProtoMessage() {}

func (x *ReleaseSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSandboxResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *ReleaseSandboxResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type InspectSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectSandboxRequest) Reset() {
	*x = InspectSandboxRequest{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectSandboxRequest) ProtoMessage() {}

func (x *InspectSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectSandboxRequest.ProtoReflect.Descriptor instead.
func (*InspectSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *InspectSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type InspectSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	State         SandboxResourceState   `protobuf:"varint,2,opt,name=state,proto3,enum=cubelet.services.runtime.v1.SandboxResourceState" json:"state,omitempty"`
	Sandbox       *PreparedSandbox       `protobuf:"bytes,3,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectSandboxResponse) Reset() {
	*x = InspectSandboxResponse{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectSandboxResponse) ProtoMessage() {}

func (x *InspectSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectSandboxResponse.ProtoReflect.Descriptor instead.
func (*InspectSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *InspectSandboxResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *InspectSandboxResponse) GetState() SandboxResourceState {
	if x != nil {
		return x.State
	}
	return SandboxResourceState_SANDBOX_RESOURCE_STATE_UNSPECIFIED
}

func (x *InspectSandboxResponse) GetSandbox() *PreparedSandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *InspectSandboxResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ReconcileSandboxesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LiveSandboxIds []string               `protobuf:"bytes,1,rep,name=live_sandbox_ids,json=liveSandboxIds,proto3" json:"live_sandbox_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconcileSandboxesRequest) Reset() {
	*x = ReconcileSandboxesRequest{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileSandboxesRequest) ProtoMessage() {}

func (x *ReconcileSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ReconcileSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *ReconcileSandboxesRequest) GetLiveSandboxIds() []string {
	if x != nil {
		return x.LiveSandboxIds
	}
	return nil
}

type ReconcileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Disposition   ReconcileDisposition   `protobuf:"varint,3,opt,name=disposition,proto3,enum=cubelet.services.runtime.v1.ReconcileDisposition" json:"disposition,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileEntry) Reset() {
	*x = ReconcileEntry{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileEntry) ProtoMessage() {}

func (x *ReconcileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileEntry.ProtoReflect.Descriptor instead.
func (*ReconcileEntry) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *ReconcileEntry) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReconcileEntry) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ReconcileEntry) GetDisposition() ReconcileDisposition {
	if x != nil {
		return x.Disposition
	}
	return ReconcileDisposition_RECONCILE_DISPOSITION_UNSPECIFIED
}

func (x *ReconcileEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ReconcileSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReconcileEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileSandboxesResponse) Reset() {
	*x = ReconcileSandboxesResponse{}
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileSandboxesResponse) ProtoMessage() {}

func (x *ReconcileSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_runtime_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ReconcileSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_api_services_runtime_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *ReconcileSandboxesResponse) GetEntries() []*ReconcileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_api_services_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_api_services_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"%api/services/runtime/v1/runtime.proto\x12\x1bcubelet.services.runtime.v1\"F\n" +
	"\x16GetCapabilitiesRequest\x12,\n" +
	"\x12client_api_version\x18\x01 \x01(\rR\x10clientApiVersion\":\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"\xda\x01\n" +
	"\x17GetCapabilitiesResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\rR\n" +
	"apiVersion\x12K\n" +
	"\fcapabilities\x18\x02 \x03(\v2'.cubelet.services.runtime.v1.CapabilityR\fcapabilities\x12!\n" +
	"\fservice_mode\x18\x03 \x01(\tR\vserviceMode\x12.\n" +
	"\x13fd_handoff_endpoint\x18\x04 \x01(\tR\x11fdHandoffEndpoint\"k\n" +
	"\vPodIdentity\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\"S\n" +
	"\x0fResourceRequest\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x01 \x01(\rR\tvcpuCount\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\"~\n" +
	"\rNetworkIntent\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x01 \x01(\tR\tnetnsPath\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x15\n" +
	"\x06pod_ip\x18\x03 \x01(\tR\x05podIp\x12\x10\n" +
	"\x03dns\x18\x04 \x03(\tR\x03dns\"\xcd\x02\n" +
	"\x15PrepareSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12:\n" +
	"\x03pod\x18\x04 \x01(\v2(.cubelet.services.runtime.v1.PodIdentityR\x03pod\x12J\n" +
	"\tresources\x18\x05 \x01(\v2,.cubelet.services.runtime.v1.ResourceRequestR\tresources\x12D\n" +
	"\anetwork\x18\x06 \x01(\v2*.cubelet.services.runtime.v1.NetworkIntentR\anetwork\"\x9a\x01\n" +
	"\rRuntimeAssets\x12\x1f\n" +
	"\vkernel_path\x18\x01 \x01(\tR\n" +
	"kernelPath\x12\x1d\n" +
	"\n" +
	"agent_path\x18\x02 \x01(\tR\tagentPath\x12(\n" +
	"\x10guest_image_path\x18\x03 \x01(\tR\x0eguestImagePath\x12\x1f\n" +
	"\vshared_root\x18\x04 \x01(\tR\n" +
	"sharedRoot\"\x89\x01\n" +
	"\x05Route\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\rR\x05scope\"D\n" +
	"\bNeighbor\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"\xbe\x02\n" +
	"\x11NetworkAttachment\x12%\n" +
	"\x0enetwork_handle\x18\x01 \x01(\tR\rnetworkHandle\x12\x19\n" +
	"\btap_name\x18\x02 \x01(\tR\atapName\x120\n" +
	"\x14guest_interface_name\x18\x03 \x01(\tR\x12guestInterfaceName\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\rR\x03mtu\x12\x10\n" +
	"\x03ips\x18\x06 \x03(\tR\x03ips\x12:\n" +
	"\x06routes\x18\a \x03(\v2\".cubelet.services.runtime.v1.RouteR\x06routes\x12C\n" +
	"\tneighbors\x18\b \x03(\v2%.cubelet.services.runtime.v1.NeighborR\tneighbors\"\xf9\x01\n" +
	"\x0fPreparedSandbox\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12B\n" +
	"\x06assets\x18\x04 \x01(\v2*.cubelet.services.runtime.v1.RuntimeAssetsR\x06assets\x12H\n" +
	"\anetwork\x18\x05 \x01(\v2..cubelet.services.runtime.v1.NetworkAttachmentR\anetwork\"x\n" +
	"\x16PrepareSandboxResponse\x12F\n" +
	"\asandbox\x18\x01 \x01(\v2,.cubelet.services.runtime.v1.PreparedSandboxR\asandbox\x12\x16\n" +
	"\x06reused\x18\x02 \x01(\bR\x06reused\"\x9a\x01\n" +
	"\x15ReleaseSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"4\n" +
	"\x16ReleaseSandboxResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"6\n" +
	"\x15InspectSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xde\x01\n" +
	"\x16InspectSandboxResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12G\n" +
	"\x05state\x18\x02 \x01(\x0e21.cubelet.services.runtime.v1.SandboxResourceStateR\x05state\x12F\n" +
	"\asandbox\x18\x03 \x01(\v2,.cubelet.services.runtime.v1.PreparedSandboxR\asandbox\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"E\n" +
	"\x19ReconcileSandboxesRequest\x12(\n" +
	"\x10live_sandbox_ids\x18\x01 \x03(\tR\x0eliveSandboxIds\"\xbc\x01\n" +
	"\x0eReconcileEntry\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12S\n" +
	"\vdisposition\x18\x03 \x01(\x0e21.cubelet.services.runtime.v1.ReconcileDispositionR\vdisposition\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"c\n" +
	"\x1aReconcileSandboxesResponse\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.cubelet.services.runtime.v1.ReconcileEntryR\aentries*\xf3\x01\n" +
	"\x14SandboxResourceState\x12&\n" +
	"\"SANDBOX_RESOURCE_STATE_UNSPECIFIED\x10\x00\x12$\n" +
	" SANDBOX_RESOURCE_STATE_PREPARING\x10\x01\x12 \n" +
	"\x1cSANDBOX_RESOURCE_STATE_READY\x10\x02\x12$\n" +
	" SANDBOX_RESOURCE_STATE_RELEASING\x10\x03\x12#\n" +
	"\x1fSANDBOX_RESOURCE_STATE_RELEASED\x10\x04\x12 \n" +
	"\x1cSANDBOX_RESOURCE_STATE_ERROR\x10\x05*\xac\x01\n" +
	"\x14ReconcileDisposition\x12%\n" +
	"!RECONCILE_DISPOSITION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRECONCILE_DISPOSITION_LIVE\x10\x01\x12*\n" +
	"&RECONCILE_DISPOSITION_ORPHAN_CANDIDATE\x10\x02\x12!\n" +
	"\x1dRECONCILE_DISPOSITION_MISSING\x10\x032\x88\x05\n" +
	"\x0fRuntimeResource\x12|\n" +
	"\x0fGetCapabilities\x123.cubelet.services.runtime.v1.GetCapabilitiesRequest\x1a4.cubelet.services.runtime.v1.GetCapabilitiesResponse\x12y\n" +
	"\x0ePrepareSandbox\x122.cubelet.services.runtime.v1.PrepareSandboxRequest\x1a3.cubelet.services.runtime.v1.PrepareSandboxResponse\x12y\n" +
	"\x0eReleaseSandbox\x122.cubelet.services.runtime.v1.ReleaseSandboxRequest\x1a3.cubelet.services.runtime.v1.ReleaseSandboxResponse\x12y\n" +
	"\x0eInspectSandbox\x122.cubelet.services.runtime.v1.InspectSandboxRequest\x1a3.cubelet.services.runtime.v1.InspectSandboxResponse\x12\x85\x01\n" +
	"\x12ReconcileSandboxes\x126.cubelet.services.runtime.v1.ReconcileSandboxesRequest\x1a7.cubelet.services.runtime.v1.ReconcileSandboxesResponseBMZKgithub.com/tencentcloud/CubeSandbox/Cubelet/api/services/runtime/v1;runtimeb\x06proto3"

var (
	file_api_services_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_api_services_runtime_v1_runtime_proto_rawDescData []byte
)

func file_api_services_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_api_services_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_api_services_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_runtime_v1_runtime_proto_rawDesc), len(file_api_services_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_api_services_runtime_v1_runtime_proto_rawDescData
}

var file_api_services_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_services_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_services_runtime_v1_runtime_proto_goTypes = []any{
	(SandboxResourceState)(0),          // 0: cubelet.services.runtime.v1.SandboxResourceState
	(ReconcileDisposition)(0),          // 1: cubelet.services.runtime.v1.ReconcileDisposition
	(*GetCapabilitiesRequest)(nil),     // 2: cubelet.services.runtime.v1.GetCapabilitiesRequest
	(*Capability)(nil),                 // 3: cubelet.services.runtime.v1.Capability
	(*GetCapabilitiesResponse)(nil),    // 4: cubelet.services.runtime.v1.GetCapabilitiesResponse
	(*PodIdentity)(nil),                // 5: cubelet.services.runtime.v1.PodIdentity
	(*ResourceRequest)(nil),            // 6: cubelet.services.runtime.v1.ResourceRequest
	(*NetworkIntent)(nil),              // 7: cubelet.services.runtime.v1.NetworkIntent
	(*PrepareSandboxRequest)(nil),      // 8: cubelet.services.runtime.v1.PrepareSandboxRequest
	(*RuntimeAssets)(nil),              // 9: cubelet.services.runtime.v1.RuntimeAssets
	(*Route)(nil),                      // 10: cubelet.services.runtime.v1.Route
	(*Neighbor)(nil),                   // 11: cubelet.services.runtime.v1.Neighbor
	(*NetworkAttachment)(nil),          // 12: cubelet.services.runtime.v1.NetworkAttachment
	(*PreparedSandbox)(nil),            // 13: cubelet.services.runtime.v1.PreparedSandbox
	(*PrepareSandboxResponse)(nil),     // 14: cubelet.services.runtime.v1.PrepareSandboxResponse
	(*ReleaseSandboxRequest)(nil),      // 15: cubelet.services.runtime.v1.ReleaseSandboxRequest
	(*ReleaseSandboxResponse)(nil),     // 16: cubelet.services.runtime.v1.ReleaseSandboxResponse
	(*InspectSandboxRequest)(nil),      // 17: cubelet.services.runtime.v1.InspectSandboxRequest
	(*InspectSandboxResponse)(nil),     // 18: cubelet.services.runtime.v1.InspectSandboxResponse
	(*ReconcileSandboxesRequest)(nil),  // 19: cubelet.services.runtime.v1.ReconcileSandboxesRequest
	(*ReconcileEntry)(nil),             // 20: cubelet.services.runtime.v1.ReconcileEntry
	(*ReconcileSandboxesResponse)(nil), // 21: cubelet.services.runtime.v1.ReconcileSandboxesResponse
}
var file_api_services_runtime_v1_runtime_proto_depIdxs = []int32{
	3,  // 0: cubelet.services.runtime.v1.GetCapabilitiesResponse.capabilities:type_name -> cubelet.services.runtime.v1.Capability
	5,  // 1: cubelet.services.runtime.v1.PrepareSandboxRequest.pod:type_name -> cubelet.services.runtime.v1.PodIdentity
	6,  // 2: cubelet.services.runtime.v1.PrepareSandboxRequest.resources:type_name -> cubelet.services.runtime.v1.ResourceRequest
	7,  // 3: cubelet.services.runtime.v1.PrepareSandboxRequest.network:type_name -> cubelet.services.runtime.v1.NetworkIntent
	10, // 4: cubelet.services.runtime.v1.NetworkAttachment.routes:type_name -> cubelet.services.runtime.v1.Route
	11, // 5: cubelet.services.runtime.v1.NetworkAttachment.neighbors:type_name -> cubelet.services.runtime.v1.Neighbor
	9,  // 6: cubelet.services.runtime.v1.PreparedSandbox.assets:type_name -> cubelet.services.runtime.v1.RuntimeAssets
	12, // 7: cubelet.services.runtime.v1.PreparedSandbox.network:type_name -> cubelet.services.runtime.v1.NetworkAttachment
	13, // 8: cubelet.services.runtime.v1.PrepareSandboxResponse.sandbox:type_name -> cubelet.services.runtime.v1.PreparedSandbox
	0,  // 9: cubelet.services.runtime.v1.InspectSandboxResponse.state:type_name -> cubelet.services.runtime.v1.SandboxResourceState
	13, // 10: cubelet.services.runtime.v1.InspectSandboxResponse.sandbox:type_name -> cubelet.services.runtime.v1.PreparedSandbox
	1,  // 11: cubelet.services.runtime.v1.ReconcileEntry.disposition:type_name -> cubelet.services.runtime.v1.ReconcileDisposition
	20, // 12: cubelet.services.runtime.v1.ReconcileSandboxesResponse.entries:type_name -> cubelet.services.runtime.v1.ReconcileEntry
	2,  // 13: cubelet.services.runtime.v1.RuntimeResource.GetCapabilities:input_type -> cubelet.services.runtime.v1.GetCapabilitiesRequest
	8,  // 14: cubelet.services.runtime.v1.RuntimeResource.PrepareSandbox:input_type -> cubelet.services.runtime.v1.PrepareSandboxRequest
	15, // 15: cubelet.services.runtime.v1.RuntimeResource.ReleaseSandbox:input_type -> cubelet.services.runtime.v1.ReleaseSandboxRequest
	17, // 16: cubelet.services.runtime.v1.RuntimeResource.InspectSandbox:input_type -> cubelet.services.runtime.v1.InspectSandboxRequest
	19, // 17: cubelet.services.runtime.v1.RuntimeResource.ReconcileSandboxes:input_type -> cubelet.services.runtime.v1.ReconcileSandboxesRequest
	4,  // 18: cubelet.services.runtime.v1.RuntimeResource.GetCapabilities:output_type -> cubelet.services.runtime.v1.GetCapabilitiesResponse
	14, // 19: cubelet.services.runtime.v1.RuntimeResource.PrepareSandbox:output_type -> cubelet.services.runtime.v1.PrepareSandboxResponse
	16, // 20: cubelet.services.runtime.v1.RuntimeResource.ReleaseSandbox:output_type -> cubelet.services.runtime.v1.ReleaseSandboxResponse
	18, // 21: cubelet.services.runtime.v1.RuntimeResource.InspectSandbox:output_type -> cubelet.services.runtime.v1.InspectSandboxResponse
	21, // 22: cubelet.services.runtime.v1.RuntimeResource.ReconcileSandboxes:output_type -> cubelet.services.runtime.v1.ReconcileSandboxesResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_services_runtime_v1_runtime_proto_init() }
func file_api_services_runtime_v1_runtime_proto_init() {
	if File_api_services_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_runtime_v1_runtime_proto_rawDesc), len(file_api_services_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_api_services_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_api_services_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_api_services_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_api_services_runtime_v1_runtime_proto = out.File
	file_api_services_runtime_v1_runtime_proto_goTypes = nil
	file_api_services_runtime_v1_runtime_proto_depIdxs = nil
}
