FROM alpine:3.22

RUN apk add --no-cache \
      busybox-extras \
      iproute2 \
      ipset \
      iptables \
      iptables-legacy \
      kmod

COPY configurer/ /opt/cube-egress/
RUN chmod 0755 /opt/cube-egress/*.sh \
    && mkdir -p /run/cube-egress /usr/local/sbin \
    && ln -s /usr/sbin/iptables-legacy /usr/local/sbin/iptables \
    && ln -s /usr/sbin/iptables-legacy-save /usr/local/sbin/iptables-save \
    && ln -s /usr/sbin/iptables-legacy-restore /usr/local/sbin/iptables-restore

ENTRYPOINT ["/opt/cube-egress/entrypoint.sh"]
